### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by moychal** [getexposure/exposure-android#21]
Occasionally gives this build error while running, and doesn't launch the app on the mulator:

02-23 17:11:13.902 1585-2475/? I/Backup: [BackupTransportMigratorService] Starting migration...
02-23 17:11:13.904 1585-2475/? E/Backup: [LegacyBackupAccountManager] Fail to get legacy transport context.
                                         android.content.pm.PackageManager$NameNotFoundException: Application package com.google.android.backup not found
                                             at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1703)
                                             at android.app.ContextImpl.createPackageContext(ContextImpl.java:1679)
                                             at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:746)
                                             at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:746)
                                             at com.google.android.gms.backup.as.<init>(SourceFile:47)
                                             at com.google.android.gms.backup.BackupTransportMigratorService.a(SourceFile:150)
                                             at com.google.android.gms.backup.BackupTransportMigratorService.onHandleIntent(SourceFile:82)
                                             at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:148)
                                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by moychal** [comment]
Old update, but build worked after minor fixes to syntax in dependencies.
