### ISSUE TITLE
ListActivity crashes on startup

### ISSUE THREAD

**Issue by moychal** [getexposure/exposure-android#35]
Log:

`02-26 22:50:18.339 2282-2438/io.github.getExposure E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9bf59830
02-26 22:50:25.148 2282-2424/io.github.getExposure E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9bf57760
02-26 22:50:25.197 2282-2282/io.github.getExposure I/Google Maps Android API: Google Play services package version: 8489470
02-26 22:50:25.234 2282-2428/io.github.getExposure E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                     Process: io.github.getExposure, PID: 2282
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{7204136 2282:io.github.getExposure/u0a58} (pid=2282, uid=10058) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
                                                                         at android.os.Parcel.readException(Parcel.java:1599)
                                                                         at android.os.Parcel.readException(Parcel.java:1552)
                                                                         at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
                                                                         at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
                                                                         at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
                                                                         at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
                                                                         at android.content.ContentResolver.query(ContentResolver.java:475)
                                                                         at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
                                                                         at android.content.CursorLoader.loadInBackground(CursorLoader.java:56)
                                                                         at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
                                                                         at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                                                                         at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818) `

To be fixed ASAP.

**Comment by moychal** [comment]
Fixed problem, there were interfering activities in the xml.
