### ISSUE TITLE
Clicking a pin->loading the photo in LocationView crashes

### ISSUE THREAD

**Issue by moychal** [getexposure/exposure-android#42]
03-04 19:11:54.353 10735-10735/io.github.getExposure E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: io.github.getExposure, PID: 10735
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
                                                                           at io.github.getExposure.post.LocationView.setupImageSwitcher(LocationView.java:242)
                                                                           at io.github.getExposure.post.LocationView.access$900(LocationView.java:44)
                                                                           at io.github.getExposure.post.LocationView$GetPicturesTask.onPostExecute(LocationView.java:220)
                                                                           at io.github.getExposure.post.LocationView$GetPicturesTask.onPostExecute(LocationView.java:209)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                           at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Othnia** [comment]
Bug fixed: AsyncTask issue where getFile was being called before the download completed
