### ISSUE TITLE
HttpClientErrorException: 405 Method Not Allowed

### ISSUE THREAD

**Issue by swammer5** [getexposure/exposure-android#7]
Post requests don't seem to be allowed by the web service. With a little digging, it seems like this might be related to how the REST service returns data. [Here](http://stackoverflow.com/questions/19512564/spring-405-error-for-post-method) is a relevant link to check out.

To replicate the bug, run DataDriver on an emulator in Android Studio.

Here is a partial stack trace:
`Caused by: org.springframework.web.client.HttpClientErrorException: 405 Method Not Allowed
                                                                     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
                                                                     at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
                                                                     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
                                                                     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:439)
                                                                     at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:317)
                                                                     at exposure.exposure.DatabaseManager.insert(DatabaseManager.java:122)
                                                                     at exposure.exposure.DataDriver.run(DataDriver.java:47)
                                                                     at exposure.exposure.DataDriver.onCreate(DataDriver.java:24)
                                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:148) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)`

**Comment by swammer5** [comment]
We get 404 now because the web service crashes when we contact it.

**Comment by swammer5** [comment]
Fixed. We were using the wrong http method types (PUT instead of POST). Then we were using the wrong url.
